<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to atendimento@saffira.com.br so we can send you a copy immediately.
 *
 * @category   Saffira / maxiPago
 * @package    MaxiPago_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php 
          $_code = $this->getMethodCode();
          $_standardPD = Mage::getSingleton('checkoutapi/geral');
          
          $_totals = Mage::getSingleton('adminhtml/session_quote')->getQuote()->collectTotals();  
    ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <ul class="forma_pagamento"></ul>
    </ul>
</fieldset>