<?php
/** @var MaxiPago_Payment_Block_Info_Eft $this */
/** @var Mage_Payment_Model_Info $info */
$info = $this->getInfo();
/** @var Mage_Sales_Model_Order $order */
$order = $this->getOrder();

/** @var MaxiPago_Payment_Helper_Data $helper */
$helper = Mage::helper('maxipago');

$bankCode = $info->getAdditionalInformation('bank');
$cpfCnpj = $info->getAdditionalInformation('cpf_cnpj');
$transactionId = $info->getAdditionalInformation('transaction_id');
$orderId = $info->getAdditionalInformation('order_id');
$bankName = $helper->getBank($bankCode);

$tid = $info->getAdditionalInformation('processor_transaction_id');
$nsu = $info->getAdditionalInformation('processor_reference_number');
?>
<div class="box-content">
    <p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
	<h3><?php echo $bankName; ?></h3>

    <?php if ($cpfCnpj): ?>
        <p><?php echo $this->__('CPF/CNPJ: %s', $cpfCnpj); ?></p>
    <?php endif;?>

    <?php if($tid): ?>
        <p><?php echo $this->__('TID: %s', $tid) ?></p>
    <?php endif; ?>

    <?php if($nsu): ?>
        <p><?php echo $this->__('NSU: %s', $nsu) ?></p>
    <?php endif; ?>

</div>

<?php echo $helper->getPullReportButton($order);?>
