<?php
/** @var MaxiPago_Payment_Block_Form_Eft $this */
$code = $this->getMethodCode();

/** @var MaxiPago_Payment_Helper_Data $helper */
$helper = Mage::helper('maxipago');

$banks  = $helper->getBanksAvailable();
$description = $helper->getConfig('description', $code);
?>
<fieldset class="form-list">
    <div id="payment_form_<?php echo $code; ?>" class="case maxipago-form" style="display:none;">
        <div class="card-entry">
            <div class="recommendation">
                <?php echo ($description) ? $description : $defaultDescription; ?>
            </div>
            <div class="input-box radio-flags">
                <label class="required">
                    <em>*</em><?php echo $this->__('Bank') ?>
                </label>
                <?php foreach ($banks as $bank):?>
                    <?php $slug = $bank['slug']; ?>
                    <label>
                        <input type="radio"
                               name="payment[bank]"
                               class="input-box maxipago_eft_bank validate-one-required-by-name"
                               id="maxipago_eft_bank_<?php echo $bank['value']; ?>"
                               value="<?php echo $bank['value']; ?>"
                               title="<?php echo $this->__('Bank') ?>"
                        />

                        <img src="<?php echo Mage::getBaseUrl('js'); ?>maxipago/banks/<?php echo $slug; ?>.png"
                             alt="<?php echo $this->__($bank['label']) ?>"
                             title="<?php echo $this->__($bank['label']) ?>"
                        />

                    </label>
                <?php endforeach; ?>
            </div>

            <?php if ($helper->getConfig('show_taxvat_field')): ?>
                <div id="divcpf" class="cpf-input input-box">
                    <label class="required">
                        <em>*</em> <?php echo $this->__('Buyer\'s CPF/CNPJ'); ?>
                    </label>
                    <input type="text"
                           placeholder="<?php echo $this->__('Only Digits'); ?>"
                           id="<?php echo $code ?>_cpf"
                           class="required-entry input-text"
                           maxlength="14"
                           name="payment[cpf_cnpj]"
                           title="<?php echo $this->__('CPF / CNPJ'); ?>"
                           value="<?php echo $this->getInfoData('cpf_cnpj') ?>"/>
                </div>
            <?php endif;?>
        </div>
    </div>
</fieldset>
<script type="text/javascript">
    $j('#payment_form_<?php echo $code ?> input.maxipago_eft_bank').click(function(){
        $j('#payment_form_<?php echo $code ?> input.maxipago_eft_bank').parent().find('img').css({'filter': 'grayscale(100%)', 'transition': '1s'});
        $j(this).parent().find('img').css({'filter': 'grayscale(0)', 'transition': '0.2s'});
    });
</script>