<?php

/**

 * Magento

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to the Open Software License (OSL 3.0)

 * that is bundled with this package in the file LICENSE.txt.

 * It is also available through the world-wide-web at this URL:

 * http://opensource.org/licenses/osl-3.0.php

 * If you did not receive a copy of the license and are unable to

 * obtain it through the world-wide-web, please send an email

 * to atendimento@saffira.com.br so we can send you a copy immediately.

 *

 * @category   Saffira / maxiPago

 * @package    MaxiPago_CheckoutApi

 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)

 */

?>

<fieldset class="form-list">

    <?php 

          $_code = $this->getMethodCode();
          
          $_bankSlip = $this->getBankSlip();

    ?>

    <style>

        ul.mpContainer li.mpPaymentMethod{

            float: left;

            padding: 5px;

            width: 80px;

            height: 30px;

        }

        ul.mpContainer li input{

            float: left;

            margin-right: 5px;

        }

        ul.mpContainer li span.mpPaymentFlag{

            float: left;

            width: 60px;

            height: 50px;

            background-image: url(<?php echo $this->getSkinUrl('maxipago/checkoutapi/images/paymentFlags1.png'); ?>);

            background-repeat: no-repeat;

        }

        /* Boleto */

        ul.mpContainer li span.mpPaymentFlagBL{

            background-position: -556px -8px;

        }

    </style>

    <ul id="payment_form_<?php echo $_code ?>" class="mpContainer" style="display:none">
	 
        <li class="forma_pagamento" style="float:left;">

            <ul>

                <li>

                    <input type="hidden" id="mpBankSlipPaymentMethod" name="payment[cc_type]" class="required-entry" value="<?php echo $_bankSlip;?>" />

                    <ul>
                                               
                        <?php if ($_bankSlip != ''):?>

                        <li class="mpPaymentMethod">


                            <span class="mpPaymentFlag mpPaymentFlagBL">

                                &nbsp;

                            </span>

                        </li>

                        <?php endif;?>

                    </ul>

                </li>

            </ul>

        </li>

    </ul>

</fieldset>