<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to atendimento@saffira.com.br so we can send you a copy immediately.
 *
 * @category   Saffira / maxiPago
 * @package    MaxiPago_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
	$_method = $this->getMethod();
    $_code = $this->getMethodCode();
    $_quote = Mage::getSingleton('checkout/session')->getQuote();
    $_totals = $_quote->collectTotals();
    $_isRecurring = $this->hasRecurringProducts();
    
    $_savedCreditcards = null;
    if($_method->getConfigData('isCCtoken')) {
        $_savedCreditcards = $this->getSavedCreditcards();
    }
    $_hasSavedCc = ($_savedCreditcards != null && is_array($_savedCreditcards) && count($_savedCreditcards) > 0);
?>
    
    <style>
        ul.mpContainer li.mpPaymentMethod{
            float: left;
            padding: 5px;
            width: 80px;
            height: 30px;
        }
        ul.mpContainer li input{
            float: left;
            margin-right: 5px;
        }
        ul.mpContainer li span.mpPaymentFlag{
            float: left;
            width: 60px;
            height: 50px;
            background-image: url(<?php echo $this->getSkinUrl('maxipago/checkoutapi/images/paymentFlags1.png'); ?>);
            background-repeat: no-repeat;
            opacity: 0.4;
            filter: alpha(opacity=40); /* For IE8 and earlier */
        }
        /* Diners */
        ul.mpContainer li span.mpPaymentFlagDC{
            background-position: -184px -8px;
        }
        /* Visa */
        ul.mpContainer li span.mpPaymentFlagVI{
            background-position: 1px -8px;
        }
        /* Master */
        ul.mpContainer li span.mpPaymentFlagMC{
            background-position: -60px -8px;
        }
        /* Amex */
        ul.mpContainer li span.mpPaymentFlagAM{
            background-position: -123px -8px;
        }
        /* Discover */
        ul.mpContainer li span.mpPaymentFlagDI{
            background-position: -308px -8px;
        }
        /* Elo */
        ul.mpContainer li span.mpPaymentFlagELO{
            background-position: -246px -8px;
        }
        /* Aura */
        ul.mpContainer li span.mpPaymentFlag18{
            background-position: -431px -8px;
        }
        /* JCB */
        ul.mpContainer li span.mpPaymentFlag19{
            background-position: -494px -8px;
        }
        ul.mpContainer li span.mpPaymentFlagHC{
            float: left;
            width: 60px;
            height: 50px;
            background-image: url(<?php echo $this->getSkinUrl('maxipago/checkoutapi/images/hipercard.png'); ?>);
            background-repeat: no-repeat;
            background-position: 0 5px;
            opacity: 0.4;
            filter: alpha(opacity=40); /* For IE8 and earlier */
        }
        .mpPaymentFlagSelected {
            opacity: 1 !important;
            filter: alpha(opacity=100) !important; /* For IE8 and earlier */
        }
        .paymentData{
            padding-left: 20px;
        }
        .mpPaymentCCSaveSelected {
            opacity: 1 !important;
            filter: alpha(opacity=100) !important; /* For IE8 and earlier */
        }
        .mpPaymentCCSave{
            opacity: 0.4;
            filter: alpha(opacity=40); /* For IE8 and earlier */
            cursor: pointer;
        }
    </style>
    
    <fieldset class="form-list">
    
    <ul id="payment_form_<?php echo $_code ?>" class="mpContainer" style="display:none">
    <?php
    if($_hasSavedCc) {
    ?>
    <li id='selectCreditCardMp' class="cc_save" style="float:left;width: 100%;">
        <label for="mpPaymentMethod"><?php echo Mage::helper('payment')->__('Selecione o cartão para realizar o pagamento') ?> <span class="required">*</span></label><br/>
        <input type="hidden" id="mpCCType" value="" />
        <input type="hidden" id="mpEntityId" name="payment[maxipago_cc_token]" class="required-entry" value="" />
        <input type="hidden" id="mpCcLast4" name="payment[cc_last4]" value="" />
        <input type="hidden" id="mpCcOwner" name="payment[cc_owner]" value="" />
        <?php
        foreach($_savedCreditcards as $_ccMaxiPago) {
        ?>
            <ul>
                <li id="ccEntity<?php echo $_ccMaxiPago['entity_id'] ?>" class="mpPaymentMethod mpPaymentCCSave" style="width: 50%;min-height: 60px;" 
                	onclick="selectCCSaved(this, '<?php echo $_ccMaxiPago['cc_type']?>', '<?php echo $_ccMaxiPago['maxipago_cc_token']?>', '<?php echo $_ccMaxiPago['cc_owner']?>', '<?php echo $_ccMaxiPago['cc_last4']?>')">
                    <span id="mpPaymentSaveFlag<?php echo $_ccMaxiPago['cc_type']?>" class="mpPaymentFlag mpPaymentFlag<?php echo $_ccMaxiPago['cc_type']?> mpPaymentFlagSelected">
                        &nbsp;
                    </span>
                    <span class="paymentData">Nome do Titular: <?php echo $_ccMaxiPago['cc_owner'] ?></span><br/>
                    <span class="paymentData">Número do Cartão: <?php echo str_pad($_ccMaxiPago['cc_last4'], 14, 'X', STR_PAD_LEFT); ?></span><br/>
                    <span class="paymentData">Mês / Ano de Vecimento: <?php echo str_pad($_ccMaxiPago['cc_exp_month'], 2, '0', STR_PAD_LEFT) . '/' . $_ccMaxiPago['cc_exp_year']?></span>
                </li>
            </ul>
        <?php
        }
        ?>
        <ul>
            <li>
                <a href="javascript:void(0)" onclick="addNewCardMaxiPago('<?php echo $_code ?>')" >Inserir outro Cartão de Cédito</a>
            </li>
        </ul>
    </li>
    <li id='newCreditCardMp' class="forma_pagamento" style="float:left;width: 100%;display: none;">
    <ul>
    <li>
        <a href="javascript:void(0)" onclick="selectCardMaxiPago('<?php echo $_code ?>')" >Selecionar um Cartão de Cédito</a>
    </li>
    <?php
    }
    else {
    ?>
    <li class="forma_pagamento" style="float:left;width: 100%;">
        <ul>
    <?php
    }
    ?>
            <li>
                <label for="mpPaymentMethod"><?php echo Mage::helper('payment')->__('Insira os dados do cartão') ?> <span class="required">*</span></label><br/>
                <input type="hidden" id="mpPaymentMethod" name="payment[cc_type]" class="required-entry" value="" />
                <ul>
                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagVI" class="mpPaymentFlag mpPaymentFlagVI">
                                &nbsp;
                            </span>
                        </li>
                        
                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagMC" class="mpPaymentFlag mpPaymentFlagMC">
                                &nbsp;
                            </span>
                        </li>
                        
                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagDC" class="mpPaymentFlag mpPaymentFlagDC">
                                &nbsp;
                            </span>
                        </li>

                        <li class="mpPaymentMethod">
                        	<span id="mpPaymentFlagAM" class="mpPaymentFlag mpPaymentFlagAM">
                                &nbsp;
                            </span>
                        </li>
                            
                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagELO" class="mpPaymentFlag mpPaymentFlagELO">
                                &nbsp;
                            </span>
                        </li>
                        
                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagDI" class="mpPaymentFlag mpPaymentFlagDI">
                                &nbsp;
                            </span>
                        </li>

                        <li class="mpPaymentMethod">
                            <span id="mpPaymentFlagHC" class="mpPaymentFlagHC">
                                &nbsp;
                            </span>
                        </li>
                </ul>
            </li>
        </ul>
    </li>
    <?php
    if($_hasSavedCc) {
    ?>
    <li id="displayCcInfo" style="display: none;">
    <?php
    }
    else {
    ?>
    <li id="displayCcInfo" style="display: block;">
    <?php
    }
    ?>
        <ul>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
                    <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" value=""
                    	onchange="document.getElementById('mpCcOwner').value = this.value;" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number" value="" maxlength="16" onkeyup="identificarCartaoCredito(this.value);"/>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
                    <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k ?>" ><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k ?>" ><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
        </ul>
    </li>
    <?php
    if(!$_isRecurring) {
    ?>
    <li>
    	<div class="input-box">
	        <input type="hidden" id="<?php echo $_code ?>_split_value" name="payment[maxipago_split_value]" value="<?php echo $this->getInfoData('maxipago_split_value')?>"/>
	        <label for="<?php echo $_code ?>_split"><?php echo Mage::helper('payment')->__('Parcelas') ?> <span class="required">*</span></label><br/>
	        <select id="<?php echo $_code ?>_split" style="width:140px;" name="payment[maxipago_split_number]" class="required-entry" onchange="document.getElementById('<?php echo $_code ?>_split_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,/,'.');">
	        	<?php $_ccSplitSimulator = $this->getInfoData('maxipago_split_number') ?>
	        	<?php foreach ($this->getSplitSimulate($_totals->grand_total) as $k=>$v): ?>
	            	<option value="<?php echo $k ?>" ><?php echo $v ?></option>
	            <?php endforeach ?>
	        </select>
        </div>
    </li>
    <?php
    }
    ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
       	<div class="input-box">
           	<div class="v-fix">
               	<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
        	<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    </ul>
    </fieldset>
