
<?php

	$_processorType = $this->getConfig('processorType');
	$_fraudCheck = $this->getConfig('fraudCheck') ? 'Y' : 'N';
	
	if($_processorType != 'sale' && $_fraudCheck == 'Y') {
		$_fraudProcessor = $this->getConfig('fraudProcessor');
		if($_fraudProcessor == '97' || $_fraudProcessor == '98') {
			$_clearSaleApp = $this->getConfig('clearSaleApp');
			
?>

			<script>
				(function (a, b, c, d, e, f, g) {
					a['CsdpObject'] = e; a[e] = a[e] || function () {
						(a[e].q = a[e].q || []).push(arguments)
					},
					a[e].l = 1 * new Date(); f = b.createElement(c),
					g = b.getElementsByTagName(c)[0]; f.async = 1; f.src = d;
					g.parentNode.insertBefore(f, g)
				})
				(window, document, 'script', '//device.clearsale.com.br/p/fp.js','csdp');
				csdp('app', '<?php echo $_clearSaleApp; ?>');
				csdp('sessionid', '<?php echo Mage::getSingleton("core/session")->getEncryptedSessionId(); ?>');
			</script>
		
<?php
		}
		elseif($_fraudProcessor == '99') {
			$_quote = Mage::getSingleton('checkout/session')->getQuote();
			$_quote->reserveOrderId()->save();
			$_sellerId = Mage::helper('checkoutapi')->getGlobalConfig('sellerId');
			$_secretKey = Mage::helper('checkoutapi')->getGlobalConfig('secretKey');
			$_orderNum = $this->getConfig('prefixo').$_quote->getReservedOrderId();
			$_hash = hash_hmac('md5', $_sellerId.'*'.$_orderNum, $_secretKey);
			$_sandbox = Mage::helper('checkoutapi')->getGlobalConfig('sandbox');
			if ($_sandbox == '1')
				$_urlFrame = 'https://testauthentication.maxipago.net/redirection_service/logo';
			else
				$_urlFrame = 'https://authentication.maxipago.net/redirection_service/logo';
?>

			<div style="display:none;">
		    	<iframe width="0" height="0" frameborder="0" 
		    		src="<?php echo $_urlFrame;?>?m=<?php echo $_sellerId;?>&s=<?php echo $_orderNum;?>&h=<?php echo $_hash;?>"></iframe>
		   	</div>
					
<?php
		}
	}
?>