<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to atendimento@saffira.com.br so we can send you a copy immediately.
 *
 * @category   Saffira / maxiPago
 * @package    MaxiPago_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<fieldset class="form-list">
    <?php 
          $_code = $this->getMethodCode();
          $_mpTefPayment = Mage::getSingleton('checkoutapi/tef');
          $_totals = Mage::getSingleton('checkout/session')->getQuote()->collectTotals();  
          
          $_quote = Mage::getSingleton('checkout/session')->getQuote();
		  
          $sandbox = Mage::helper('checkoutapi')->getGlobalConfig('sandbox');
          $paymentTef = explode(",",$_mpTefPayment->getConfigData("paymentTef"));
          $qtdTef = sizeof($paymentTef);
    ?>
    
    <style>
        ul.mpContainer li.mpPaymentMethod{
            float: left;
            padding: 5px;
            width: 80px;
            height: 30px;
        }
        ul.mpContainer li input{
            float: left;
            margin-right: 5px;
        }
        ul.mpContainer li span.mpPaymentFlag{
            float: left;
            width: 60px;
            height: 50px;
            background-image: url(<?php echo $this->getSkinUrl('maxipago/checkoutapi/images/paymentFlags1.png'); ?>);
            background-repeat: no-repeat;
        }
        /* Itaú */
        ul.mpContainer li span.mpPaymentFlagIT{
            background-position: -618px -8px;
        }
        /* Bradesco */
        ul.mpContainer li span.mpPaymentFlagBR{
            background-position: -679px -8px;
        }
        /* Banco do Brasil */
        ul.mpContainer li span.mpPaymentFlag23{
            background-position: -741px -8px;
        }
    </style>
    
    <ul id="payment_form_<?php echo $_code ?>" class="mpContainer" style="display:none">
	 
        <li class="forma_pagamento" style="float:left;">
            <ul>
                <li>
                	<?php if ($sandbox != '1'):?>
                    	<input type="hidden" id="mpTefPaymentMethod" name="payment[cc_type]" class="required-entry" value="18"/>
					<?php elseif ($qtdTef == 1):?>
						<input type="hidden" id="mpTefPaymentMethod" name="payment[cc_type]" class="required-entry" value="<?php echo $paymentTef[0]; ?>"/>
					<?php else:?>
						<label for="mpTefPaymentMethod"><?php echo Mage::helper('payment')->__('Selecione a forma de pagamento') ?> <span class="required">*</span></label><br/>
                        <input type="hidden" id="mpTefPaymentMethod" name="payment[cc_type]" class="required-entry" value="<?php if($qtdTef == 1){ echo $paymentTef[0];} ?>"/>
					<?php endif;?>
                    <ul>
                        <?php
                        if (in_array("17", $paymentTef) && $sandbox == '1'){
                        ?>

                        <li class="mpPaymentMethod">
                            <?php
                                if($qtdTef != 1){
                            ?>
                            	<input type="radio" onclick="document.getElementById('mpTefPaymentMethod').value = this.value; document.getElementById('displayCcInfo').style.display = 'none'" value="17" name="mpTefPaymentMethodR" autocomplete="off">
                            <?php
                            }
                            ?>
                            <span class="mpPaymentFlag mpPaymentFlagBR">
                                &nbsp;
                            </span>
                        </li>
						 
                        <?php
                        }
                        ?>
                        <?php
                        if (in_array("18", $paymentTef)){
                        ?>
                        <li class="mpPaymentMethod">
                            <?php
                            if($qtdTef != 1 && $sandbox == '1'){
                            ?>
								<input type="radio" onclick="document.getElementById('mpTefPaymentMethod').value = this.value; document.getElementById('displayCcInfo').style.display = 'none'" value="18" name="mpTefPaymentMethodR" autocomplete="off">
                            <?php
                            }
                            ?>

                            <span class="mpPaymentFlag mpPaymentFlagIT">
                                &nbsp;
                            </span>
                        </li>
                        <?php
                        }
                        ?>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</fieldset>