<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to atendimento@saffira.com.br so we can send you a copy immediately.
 *
 * @category   Saffira / maxiPago
 * @package    MaxiPago_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$title = "";
$message = "";
?>
<?php
    if($this->getRequest()->getParam("type") == 'G' || $this->getRequest()->getParam("type") == 'V'){
        $title = "Erro ao realizar seu pedido.";
        $message = "Ocorreu um erro ao realizar o seu pedido.";

    }else{
        $title = "Erro ao realizar o Retorno Autom&aacute;tico";
        $message = "Ocorreu um erro ao realizar o retorno autom&aacute;tico.";
    }
?>
<div class="page-head">
    
    <h2 class="sub-title"><?php echo $title;?></h2>
</div>
<table style="width:100%;">
    <tr>
        <td style="width:100%">
            <?php echo $message;?><br /><br />
            Dados do Erro:<br />
            <?php
                if($this->getRequest()->getParam("type") == 'V'){
            ?>
            Campos: <?php echo utf8_decode($this->getRequest()->getParam("codigo"));  ?><br />
            <?php 
                }else{
            ?>
            C&oacute;digo: <?php echo utf8_decode($this->getRequest()->getParam("codigo"));  ?><br />
            <?php 
                }
            ?>
            Descri&ccedil;&atilde;o: <?php echo $this->getRequest()->getParam("descricao");  ?><br />
        </td>
    </tr>
</table>