<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to atendimento@saffira.com.br so we can send you a copy immediately.
 *
 * @category   Saffira / maxiPago
 * @package    MaxiPago_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div id="overlay-tc">
    <center>
        <div id="lightboxtc" style="padding: 10px;background-color: #fff;width: 980px;margin-top: 50px" >
            <img src="<?php echo $this->getSkinUrl('maxipago/checkoutapi/images/close.png'); ?>" style="position: relative;margin-left: 970px;margin-top: -20px;" />
            <iframe name="tc_frame" width="970" height="700" style="border:0px" ></iframe>
        </div>
    </center>
</div>
