
<div class="page-title">
    <h1><?php echo $this->__('Seu pedido foi recebido.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<h2 class="sub-title paying-with-info">
    <span><?php echo $this->__('Você está pagando seu pedido com maxiPago! - RedePay') ?></span>
</h2>

<?php if ($this->getOrderId()):?>
    <p><?php echo $this->__('Seu número de pedido é: %s.', $this->escapeHtml($this->getRealOrderId())) ?></p>
    <p><?php echo $this->__('Seu pedido está em processo de finalização, por favor aguarde alguns instantes.') ?></p>
    <p><?php echo $this->__('Se a página de pagamento não aparecer, clique no link abaixo.') ?></p>
    <p><a href="<?php echo $this->getAuthenticationUrl() ?>">Abrir pagamento</a></p>

    <div id="scripts-container">
        <script type="text/javascript">
	    //<![CDATA[
            setTimeout(function() {
            	window.location.replace('<?php echo $this->getAuthenticationUrl() ?>');
                $('scripts-container').hide();
            }, 5);
        //]]>
        </script>
    </div>
<?php endif;?>
