
<div class="page-title">
    <h1><?php echo $this->__('Seu pedido #%s está em análise.', $this->getRealOrderId()) ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<p><?php echo $this->__('Sua compra foi finalizada com sucesso.<br/>Estamos aguardando a confirmação do pagamento.') ?></p>

<div>
    Seu n&uacute;mero de pedido &eacute;: <strong><?php echo $this->getOrderNumber()?></strong><br />
    N&uacute;mero da transa&ccedil;&atilde;o no <?php ?>: <strong><?php echo $this->getTransactionId()?></strong><br />
    Meio de Pagamento: <strong><?php echo $this->getPaymentMethodName()?></strong><br />
    Situa&ccedil;&atilde;o da transa&ccedil;&atilde;o no <?php echo $this->getPaymentTitle(); ?>: <strong><?php echo $this->getStatusName()?></strong><br /><br />
</div>

<div class="buttons-set">
	<button type="button" class="button btn-continue" title="Imprimir Boleto" onclick="window.open('<?php echo $this->getPrintOrderUrl()?>');">
		<span><span>Imprimir Boleto</span></span>
	</button>	
	<button type="button" class="button btn-continue" title="Continuar Comprando" onclick="window.location='<?php echo $this->getUrl() ?>';">
		<span><span>Continuar Comprando</span></span>
	</button>
</div>